name: Deploy PR previews
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize    
permissions:
  contents: write
  pull-requests: write
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.3
        with:
          token: ${{ secrets.PR_preview }}
          preview-branch: pr-preview
          source-dir: .
          umbrella-dir: pr-preview
          action: auto
